#!/bin/sh

PATH=/opt/cc68/bin:/opt/fcc/bin:$PATH
#OPT=-O3
OPT=

b=$(basename $1 .c)
echo  $b":"
cc68 $OPT -m6800 -o $b $b.c 
err=$?
cc68 $OPT -m6800 -S $b.c
if [ $err -ne 0 ] ; then
	echo $err
	rm -f $b $b.o $b.s
	exit $err
fi
echo emu6800 -d 6800 $b /dev/null
#emu6800 -d 6800 $b /dev/null
emu6800 6800 $b /dev/null
result=$?
echo $result
exit $result
